# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LoadSystem.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1080, 720)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.StartButton = QtWidgets.QPushButton(self.centralwidget)
        self.StartButton.setGeometry(QtCore.QRect(890, 650, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.StartButton.setFont(font)
        self.StartButton.setObjectName("StartButton")
        self.LoadButton = QtWidgets.QPushButton(self.centralwidget)
        self.LoadButton.setGeometry(QtCore.QRect(890, 20, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.LoadButton.setFont(font)
        self.LoadButton.setObjectName("LoadButton")
        self.verticalScrollBar = QtWidgets.QScrollBar(self.centralwidget)
        self.verticalScrollBar.setGeometry(QtCore.QRect(890, 230, 31, 411))
        self.verticalScrollBar.setMaximum(100)
        self.verticalScrollBar.setPageStep(8)
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.wheel = QtWidgets.QDial(self.centralwidget)
        self.wheel.setGeometry(QtCore.QRect(930, 230, 131, 411))
        self.wheel.setPageStep(10)
        self.wheel.setProperty("value", 50)
        self.wheel.setObjectName("wheel")
        self.TextDt = QtWidgets.QTextEdit(self.centralwidget)
        self.TextDt.setGeometry(QtCore.QRect(890, 100, 181, 41))
        self.TextDt.setObjectName("TextDt")
        self.TextTimeLimit = QtWidgets.QTextEdit(self.centralwidget)
        self.TextTimeLimit.setGeometry(QtCore.QRect(890, 180, 181, 41))
        self.TextTimeLimit.setObjectName("TextTimeLimit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(890, 80, 181, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(890, 150, 181, 21))
        self.label_2.setObjectName("label_2")
        self.SpaceWidget = SpaceWidget(self.centralwidget)
        self.SpaceWidget.setGeometry(QtCore.QRect(10, 10, 871, 681))
        self.SpaceWidget.setObjectName("SpaceWidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Planet System"))
        self.StartButton.setText(_translate("MainWindow", "Start"))
        self.LoadButton.setText(_translate("MainWindow", "Load"))
        self.label.setText(_translate("MainWindow", "dt:"))
        self.label_2.setText(_translate("MainWindow", "Time limit"))
from spacewidget import SpaceWidget
